version: '2.3'

services:
   web:
     build: ./
     restart: always
     ports:
      - '9808:9808'
   redis:
     image : redis
     ports:
      - 6379:6379
   postgres:
      image: postgres
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=newPassword
        - POSTGRES_DB=url_short
        - POSTGRES_HOST=postgres
      volumes:
        - ./pg-data:/var/lib/postgresql/data